apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins-k8s.fullname" . }}
  labels:
    app: {{ template "jenkins-k8s.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      #targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "jenkins-k8s.name" . }}
    release: {{ .Release.Name }}

---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - jenkins.thetestpad.com
      secretName: jenkins-k8s-tls
  rules:
    - host: jenkins.thetestpad.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: jenkins-jenkins-k8s
              servicePort: 8080
